In [42]:
import numpy as np
from matplotlib import pyplot as plt

In [43]:
#Sigmoid Activation Function
def sigmoid(x, derive=False):
    if derive:
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [38]:
#Define the Data set OR logic
#Initialize the 8 samples of the OR function.
X = np.array([
    [1, 1, 1, 1],
    [1, 1, -1, 1],
    [1, 0, 1, 1],
    [1, -1, -1, 1],
    [-1, 1, 1, 1],
    [-1, 1, -1, 1],
    [-1, -1, 1, 1],
    [-1, -1, -1, 1],
])
indices_one = X == -1
X[indices_one] = 0 # replacing 1s with 0s
print(X)
#Define the labels of each sample.
y = np.array([[1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [1],
              [-1]
             ])

indices_one = y == -1
y[indices_one] = 0 # replacing 1s with 0s
print(y)

[[1 1 1 1]
 [1 1 0 1]
 [1 0 1 1]
 [1 0 0 1]
 [0 1 1 1]
 [0 1 0 1]
 [0 0 1 1]
 [0 0 0 1]]
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]]


In [44]:
# Define a learning rate
lr = 0.1
# Define the number of epochs for learning
epochs = 3

# Initialize the weights with random numbers
w01 = np.random.random((len(X[0]), 4))   #Initialize the hidden layer weights with ones. Size of hidden layer is 4.
w12 = np.random.random((4, 1))           #Initialize the output layer weights with ones. Size of output layer is 1.


In [41]:
# Start feeding forward and backpropagate *epochs* times.
for epoch in range(epochs):
    # Feed forward
    z_h = np.dot(X, w01) #Calculate the input of the hidden layer zh using matrix multiplication.
    #print(z_h)
    a_h = sigmoid(z_h)   #Calculate the output of the hidden layer ah using sigmoid activation function.
    #print(a_h)

    z_o = np.dot(a_h, w12)   #Calculate the input of the output layer zo using matrix multiplication.
    #print(z_o)
    a_o = sigmoid(z_o)      #Calculate the output of the output layer ao using sigmoid activation function.
    #print(a_o)

    # Calculate the error
    a_o_error = ((1 / 2) * (np.power((a_o - y), 2)))  # Calculate the error of the output neuron ao using squared error function.
    #print(a_o_error)

    # Backpropagation
    ## Output layer
    delta_a_o_error = a_o - y    #Calculate the derivate of the error of the output layer.
    #print(delta_a_o_error)
    delta_z_o = sigmoid(a_o,derive=True)  #Calculate the derivate of the sigmoid function of the output layer.
    #print(delta_z_o)
    delta_w12 = a_h    #Calculate the derivate of the input of the output layer zo with respect to the weights w.
    #print(a_h)
    delta_output_layer = np.dot(delta_w12.T,(delta_a_o_error * delta_z_o))  # Calculate the update matrix for the output layer using matrix multiplication and hadamard product.
    #print(delta_output_layer)

    ## Hidden layer
    delta_a_h = np.dot(delta_a_o_error * delta_z_o, w12.T)  #Calculate the derivate of the Error function E with respect to the output of the hidden layer ah.
    #print(delta_a_h)
    delta_z_h = sigmoid(a_h,derive=True)  #Calculate the derivate of the sigmoid of the hidden layer.
    #print(delta_z_h)
    delta_w01 = X   #Calculate the derivate of the input of the hidden layer zh with respect to the weight matrix w01.
    #print(X)
    delta_hidden_layer = np.dot(delta_w01.T, delta_a_h * delta_z_h) #Calculate the update matrix for the hidden layer using matrix multiplication and hadamard product.
    #print(delta_hidden_layer)

    w01 = w01 - lr * delta_hidden_layer
    w12 = w12 - lr * delta_output_layer
    print(w01)
    print(w12)

[[0.06385209 0.09828322 0.62829311 0.62183754]
 [0.52752095 0.93706289 0.92957938 0.16109411]
 [0.74522796 0.35365902 0.1055096  0.33429338]
 [0.96567855 0.52858341 0.41518875 0.51060044]]
[[0.07433442]
 [0.4339805 ]
 [0.71333701]
 [0.37330689]]
[[0.06400836 0.09942675 0.62990356 0.6227455 ]
 [0.52764484 0.93788195 0.9309297  0.16207118]
 [0.74535412 0.35477809 0.10745507 0.3353267 ]
 [0.96573524 0.52915359 0.41600555 0.5112246 ]]
[[0.08688154]
 [0.44605262]
 [0.72589386]
 [0.38487862]]
[[0.06418173 0.10054108 0.63145583 0.62363204]
 [0.52778183 0.93867695 0.93222662 0.16302311]
 [0.74549411 0.35586926 0.10933259 0.33633675]
 [0.9657873  0.52964381 0.41668266 0.51177708]]
[[0.09832664]
 [0.45710974]
 [0.73743114]
 [0.39546889]]
